"""add_report_fields

Revision ID: 0cfca26096db
Revises: aca612b0bad2
Create Date: 2026-06-26 18:20:45.402133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cfca26096db'
down_revision: Union[str, None] = 'aca612b0bad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('file_size_bytes', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('reports', sa.Column('ocr_engine_used', sa.String(length=100), nullable=True))
    op.add_column('reports', sa.Column('report_date', sa.String(length=50), nullable=True))
    op.add_column('reports', sa.Column('report_type', sa.String(length=100), nullable=True))
    op.add_column('reports', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'error_message')
    op.drop_column('reports', 'report_type')
    op.drop_column('reports', 'report_date')
    op.drop_column('reports', 'ocr_engine_used')
    op.drop_column('reports', 'mime_type')
    op.drop_column('reports', 'file_size_bytes')
    # ### end Alembic commands ###
