"""add_missing_chat_interaction_updated_at

Revision ID: 3aaff6385867
Revises: 9b3628c4bc13
Create Date: 2026-06-27 22:42:45.265137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaff6385867'
down_revision: Union[str, None] = '9b3628c4bc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_interactions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.create_index(op.f('ix_chat_interactions_id'), 'chat_interactions', ['id'], unique=False)
    op.drop_constraint(op.f('chat_interactions_report_id_fkey'), 'chat_interactions', type_='foreignkey')
    op.drop_constraint(op.f('chat_interactions_user_id_fkey'), 'chat_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_interactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_interactions', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_interactions', type_='foreignkey')
    op.drop_constraint(None, 'chat_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_interactions_user_id_fkey'), 'chat_interactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_interactions_report_id_fkey'), 'chat_interactions', 'reports', ['report_id'], ['id'])
    op.drop_index(op.f('ix_chat_interactions_id'), table_name='chat_interactions')
    op.drop_column('chat_interactions', 'updated_at')
    # ### end Alembic commands ###
