"""add_ai_summary

Revision ID: 9b3628c4bc13
Revises: c9794fd77c2c
Create Date: 2026-06-27 19:39:11.419596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3628c4bc13'
down_revision: Union[str, None] = 'c9794fd77c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'ai_summary')
    # ### end Alembic commands ###
