"""architecture_upgrade

Revision ID: aca612b0bad2
Revises: 
Create Date: 2026-06-26 18:18:55.268016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca612b0bad2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_markers',
    sa.Column('marker_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('normal_description', sa.Text(), nullable=True),
    sa.Column('low_meaning', sa.Text(), nullable=True),
    sa.Column('high_meaning', sa.Text(), nullable=True),
    sa.Column('possible_causes_low', sa.Text(), nullable=True),
    sa.Column('possible_causes_high', sa.Text(), nullable=True),
    sa.Column('lifestyle_recommendations', sa.Text(), nullable=True),
    sa.Column('diet_recommendations', sa.Text(), nullable=True),
    sa.Column('exercise_recommendations', sa.Text(), nullable=True),
    sa.Column('doctor_advice', sa.Text(), nullable=True),
    sa.Column('severity_information', sa.Text(), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_markers_id'), 'medical_markers', ['id'], unique=False)
    op.create_index(op.f('ix_medical_markers_marker_name'), 'medical_markers', ['marker_name'], unique=True)
    op.create_table('reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('report_markers',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('marker_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_markers_id'), 'report_markers', ['id'], unique=False)
    op.create_index(op.f('ix_report_markers_marker_name'), 'report_markers', ['marker_name'], unique=False)
    op.create_index(op.f('ix_report_markers_report_id'), 'report_markers', ['report_id'], unique=False)
    op.create_table('marker_analysis',
    sa.Column('report_marker_id', sa.UUID(), nullable=False),
    sa.Column('retrieved_knowledge_id', sa.UUID(), nullable=True),
    sa.Column('gemma_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_marker_id'], ['report_markers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieved_knowledge_id'], ['medical_markers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marker_analysis_id'), 'marker_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_marker_analysis_report_marker_id'), 'marker_analysis', ['report_marker_id'], unique=True)
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_report_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_analyses_report_status'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    
    op.drop_constraint(op.f('upload_history_report_id_fkey'), 'upload_history', type_='foreignkey')

    op.drop_index(op.f('ix_extracted_markers_id'), table_name='extracted_markers')
    op.drop_index(op.f('ix_extracted_markers_marker_name'), table_name='extracted_markers')
    op.drop_index(op.f('ix_extracted_markers_report_id'), table_name='extracted_markers')
    op.drop_index(op.f('ix_extracted_markers_severity'), table_name='extracted_markers')
    op.drop_index(op.f('ix_markers_name'), table_name='extracted_markers')
    op.drop_index(op.f('ix_markers_report_severity'), table_name='extracted_markers')
    op.drop_table('extracted_markers')

    op.drop_index(op.f('ix_medical_reports_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_status'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_user_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_reports_user_created'), table_name='medical_reports')
    op.drop_index(op.f('ix_reports_user_status'), table_name='medical_reports')
    op.drop_table('medical_reports')

    op.create_foreign_key(None, 'upload_history', 'reports', ['report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_history', type_='foreignkey')
    op.create_foreign_key(op.f('upload_history_report_id_fkey'), 'upload_history', 'medical_reports', ['report_id'], ['id'], ondelete='SET NULL')
    op.create_table('extracted_markers',
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('marker_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('numeric_value', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('reference_min', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('reference_max', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], name=op.f('extracted_markers_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('extracted_markers_pkey'))
    )
    op.create_index(op.f('ix_markers_report_severity'), 'extracted_markers', ['report_id', 'severity'], unique=False)
    op.create_index(op.f('ix_markers_name'), 'extracted_markers', ['marker_name'], unique=False)
    op.create_index(op.f('ix_extracted_markers_severity'), 'extracted_markers', ['severity'], unique=False)
    op.create_index(op.f('ix_extracted_markers_report_id'), 'extracted_markers', ['report_id'], unique=False)
    op.create_index(op.f('ix_extracted_markers_marker_name'), 'extracted_markers', ['marker_name'], unique=False)
    op.create_index(op.f('ix_extracted_markers_id'), 'extracted_markers', ['id'], unique=False)
    op.create_table('medical_reports',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('stored_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ocr_engine_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('medical_reports_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('medical_reports_pkey'))
    )
    op.create_index(op.f('ix_reports_user_status'), 'medical_reports', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_reports_user_created'), 'medical_reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_medical_reports_user_id'), 'medical_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_medical_reports_status'), 'medical_reports', ['status'], unique=False)
    op.create_index(op.f('ix_medical_reports_id'), 'medical_reports', ['id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ai_provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('health_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('abnormal_markers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('doctor_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], name=op.f('ai_analyses_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_analyses_pkey'))
    )
    op.create_index(op.f('ix_analyses_report_status'), 'ai_analyses', ['report_id', 'status'], unique=False)
    op.create_index(op.f('ix_ai_analyses_report_id'), 'ai_analyses', ['report_id'], unique=True)
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.drop_index(op.f('ix_marker_analysis_report_marker_id'), table_name='marker_analysis')
    op.drop_index(op.f('ix_marker_analysis_id'), table_name='marker_analysis')
    op.drop_table('marker_analysis')
    op.drop_index(op.f('ix_report_markers_report_id'), table_name='report_markers')
    op.drop_index(op.f('ix_report_markers_marker_name'), table_name='report_markers')
    op.drop_index(op.f('ix_report_markers_id'), table_name='report_markers')
    op.drop_table('report_markers')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_medical_markers_marker_name'), table_name='medical_markers')
    op.drop_index(op.f('ix_medical_markers_id'), table_name='medical_markers')
    op.drop_table('medical_markers')
    # ### end Alembic commands ###
